name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go build -v ./...
    - run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

    - uses: qltysh/qlty-action/coverage@v1
      continue-on-error: true
      with:
        token: {{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage.out
